"""empty message

Revision ID: 03445c2d5ea9
Revises: 
Create Date: 2021-01-09 17:51:27.478896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03445c2d5ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('goals', sa.String(length=128), nullable=True),
    sa.Column('free', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('picture')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_model')
    # ### end Alembic commands ###
