"""empty message

Revision ID: 4bf35778d365
Revises: 05ebb94c31a0
Create Date: 2021-01-10 13:15:16.797478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf35778d365'
down_revision = '05ebb94c31a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('goals', sa.String(length=128), nullable=True),
    sa.Column('free', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('picture')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_model')
    op.drop_table('teacher_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=64), nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=12, scale=1), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('goals', sa.VARCHAR(length=128), nullable=True),
    sa.Column('free', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('picture')
    )
    op.create_table('order_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    op.drop_table('teacher')
    # ### end Alembic commands ###
